### ISSUE TITLE
Silicon Plates cannot be crafted.

### ISSUE THREAD

**Issue by XikiroRavenfang** [Kasax007/Dreamcraft-Development-#75] opened 2022-12-25 15:08 UTC
**The Current Issue**
Silicon Plates from Tech Reborn cannot be crafted and no alternative recipe is shown.

**Expected behavior**
2 Silicon Cells in an Industrial Blast Furnace should produce Silicon Plates.

**Self-Testing Done**
Curseforge's Repair Profile feature was used to check if that somehow fixed the problem, to no avail. Both singleplayer and multiplayer were checked for the issue. Full reinstallation of the pack was not done since the problem appeared in both singleplayer and multiplayer so it was unlikely that the problem came from a bad install, also since I don't have server access to do a reinstallation there.

I created a fresh profile with only Tech Reborn (plus it's addons) and REI to check if the issue was on Tech Reborn's side. The crafting recipe both worked on this profile and displayed in REI.
Curseforge Test Profile (includes mods, config and resourcepack folders (Curseforge default export)):
[Test Bench.zip](https://github.com/Kasax007/Modpack-Development/files/10300169/Test.Bench.zip)

**Screenshots of the issue**
Me in a singleplayer creative world to test if bug was only server side.
![2022-12-26_01 35 51](https://user-images.githubusercontent.com/28580931/209472311-2117edb0-f473-4d1a-9dca-ba3208ec8f0f.png)
![2022-12-26_01 36 33](https://user-images.githubusercontent.com/28580931/209472314-42e1de5c-2711-4c45-8046-18a3c96857c9.png)
Me on my friends survival server (Started only 5 days ago)
![2022-12-26_01 38 28](https://user-images.githubusercontent.com/28580931/209472315-c0f950f6-cc2b-45d5-908a-4a2098309ce2.png)
![2022-12-26_01 38 34](https://user-images.githubusercontent.com/28580931/209472318-d6dfde2f-5fdd-49d2-b4d9-c3aeac9ef2ba.png)

**To Reproduce the issue**
Unsure if any steps outside of loading up the pack and checking for yourself are required to reproduce this issue. Sorry I can't be of more help here.

**Version of the modpack**
Game Version: 1.19.2
Modpack Version: Dreamcraft 1.19.2-1.0.34 (Dreamcraft 1.19.2 v6 Release)

**Additional Context**
Server provider is Shockbyte.

**Comment by NitroxydeX** [comment] 2023-01-03 19:44
This is a dupe of #73 - it's a known bug from KubeJS. It's fixed in their latest beta build -> https://www.curseforge.com/minecraft/mc-mods/kubejs/files/4238468

**Comment by Kasax007** [comment] 2023-02-16 22:22
Fixed for the upcoming update

**Closed as completed by Kasax007** 2023-02-16 22:22 UTC
Labels: bug, known issue, Will be added
